import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { DotPattern } from "@/components/ui/dot-pattern";

const spaceMono = Space_Mono({
    variable: "--font-space-mono",
    weight: ["400"],
    subsets: ["latin"],
});
const dmSans = DM_Sans({
    variable: "--font-sans",
    weight: ["400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "<Career Log/>",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="it" className="no-scrollbar">
            <body
                className={`${spaceMono.variable} ${dmSans.variable} antialiased`}
            >
                {children}
                <DotPattern className="-z-10 opacity-30" />
            </body>
        </html>
    );
}
